[package]
name = "decay"
version = "0.1.0"
authors = ["BartoszRumak <27711689+RumakBartosz@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.7" }